version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  postgresql:
    container_name: postgresql
    build: ./data/postgresql
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always
